const users = [
    {
      email: "admin@example.com",
      username: "admin",
      password: process.env.ADMINPWD,
      name: "The Boss",
      location: "Hacking Town",
      pic: "https://randomuser.me/api/portraits/men/44.jpg",
      followers: 10000,
      projects: 1337,
      ranks: 1,
      flag: process.env.MEDIUMFLAG,
    },
    {
      email: "john.doe@example.com",
      username: "john.doe",
      password: "/f3)08&6wNLc",
      name: "John Doe",
      location: "New Orleans",
      pic: "https://randomuser.me/api/portraits/men/22.jpg",
      followers: 5678,
      projects: 987,
      ranks: 2,
      flag: "flag{not_the_right_one_but_fun}",
    },
    {
      email: "alice.johnson@email.net",
      username: "alice.johnson",
      password: "r&)7`g8mLN2j",
      name: "Alice Johnson",
      location: "Denver",
      pic: "https://randomuser.me/api/portraits/women/33.jpg",
      followers: 7890,
      projects: 543,
      ranks: 3,
      flag: "flag{incorrect_flag_but_smile}",
    },
    {
      email: "elena.rodriguez@example.com",
      username: "elena.rodriguez",
      password: "1T^u£2)6g03.",
      name: "Elena Rodriguez",
      location: "New York City",
      pic: "https://randomuser.me/api/portraits/women/12.jpg",
      followers: 4321,
      projects: 876,
      ranks: 4,
      flag: "flag{fake_flag_but_lol}",
    },
    {
      email: "david.smith@example.com",
      username: "david.smith",
      password: "w4PF<1ccO?M0",
      name: "David Smith",
      location: "Los Angeles",
      pic: "https://randomuser.me/api/portraits/men/55.jpg",
      followers: 6543,
      projects: 321,
      ranks: 5,
      flag: "flag{wrong_key_but_chuckle}",
    },
    {
      email: "emma.white@example.com",
      username: "emma.white",
      password: ",0US=3YAGg1m",
      name: "Emma White",
      location: "Chicago",
      pic: "https://randomuser.me/api/portraits/women/45.jpg",
      followers: 9876,
      projects: 654,
      ranks: 6,
      flag: "flag{faux_flag_but_grin}",
    },
    {
      email: "michael.brown@example.com",
      username: "michael.brown",
      password: ")kv}8Aq-2)I1",
      name: "Michael Brown",
      location: "San Francisco",
      pic: "https://randomuser.me/api/portraits/men/11.jpg",
      followers: 5432,
      projects: 210,
      ranks: 7,
      flag: "flag{bogus_flag_but_amused}",
    },
    {
      email: "sophia.johnson@example.com",
      username: "sophia.johnson",
      password: "o1m%-]?B0j36",
      name: "Sophia Johnson",
      location: "Seattle",
      pic: "https://randomuser.me/api/portraits/women/25.jpg",
      followers: 7654,
      projects: 543,
      ranks: 8,
      flag: "flag{not_true_flag_but_giggle}",
    },
    {
      email: "christopher.lee@example.com",
      username: "christopher.lee",
      password: "m#~9H<YD37u]",
      name: "Christopher Lee",
      location: "Miami",
      pic: "https://randomuser.me/api/portraits/men/77.jpg",
      followers: 3210,
      projects: 876,
      ranks: 9,
      flag: "flag{phony_flag_but_haha}",
    },
    {
      email: "olivia.taylor@example.com",
      username: "olivia.taylor",
      password: "r0d4CR54p&aI",
      name: "Olivia Taylor",
      location: "Denver",
      pic: "https://randomuser.me/api/portraits/women/66.jpg",
      followers: 2345,
      projects: 432,
      ranks: 10,
      flag: "flag{false_flag_but_teehee}",
    },
    {
      email: "daniel.garcia@example.com",
      username: "daniel.garcia",
      password: "zbhp~gN|i030",
      name: "Daniel Garcia",
      location: "Austin",
      pic: "https://randomuser.me/api/portraits/men/33.jpg",
      followers: 8765,
      projects: 1098,
      ranks: 11,
      flag: "flag{erroneous_flag_but_snicker}",
    },
  ];

  exports.users = users;